name: Automatic Testing for BookTrack Search Function

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3

      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove existing node_modules folder
        run: rm -rf ./node_modules

      - name: Install dependencies
        run: npm install

      - name: Run backend tests
        run: npm run backend-test

      - name: Instrument the frontend code
        run: |
          cp -R public instrumented
          npx nyc instrument public instrumented

      - name: Run frontend test cases
        run: npx nyc --nycrc-path .nycrc-frontend cypress run

